buildy_platform_home:
    path:    /{page}
    defaults: { _controller: BUILDYPlatformBundle:Advert:index, page: 1 }
    requirements:
        page : \d+

buildy_platform_view:
    path:      /advert/{id}
    defaults:  { _controller: BUILDYPlatformBundle:Advert:view }
    requirements:
        id : \d+    
        
buildy_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: BUILDYPlatformBundle:Advert:edit }
    requirements:
        id: \d+

buildy_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: BUILDYPlatformBundle:Advert:delete }
    requirements:
        id: \d+
    
buildy_platform_add:
    path:      /add
    defaults:  { _controller: BUILDYPlatformBundle:Advert:add }