<?php

namespace BUILDY\PlatformBundle\Entity;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * [getApplicationsWithAdvert description]
   * @param  [type] $limit [description]
   * @return [type]        [description]
   */
  public function getApplicationsWithAdvert($limit){
     $qb = $this->createQueryBuilder('a');
      // On fait une jointure avec l'entité Advert avec pour alias « adv »
      $qb
        ->join('a.advert', 'adv')
        ->addSelect('adv')
      ;

      // Puis on ne retourne que $limit résultats
      $qb->setMaxResults($limit);

      // Enfin, on retourne le résultat
      return $qb
        ->getQuery()
        ->getResult()
        ;
  }
}
